# Building project and deploying to GitHub pages
name: Build and Deploy Site to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run dev

      - name: Deploy to Github Pages
        uses: ColeSchoe/portfolio-site@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./dist
