name: Build and Deploy Vue Portfolio Site Project to Github Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run dev

    - name: Deploy to Github Pages
      uses: ColeSchoe/portfolio-site@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./dist
